[build]
   ignore = "/bin/false"

[build.environment]
   NODE_VERSION = "20"

[[redirects]]
  from = "/docs/governance/software-projects/stages/active"
  to = "/docs/governance/lifecycle-stages/graduated"
  status = 301