name: "🐣 Project Labs"
description: To apply for the Labs lifecycle stage.
title: "Project Labs: [Project Name]"
labels: ["lifecycle", "incubation"]
assignees:
  - maoo
  - TheJuanAndOnly99
body:
  - type: markdown
    attributes:
      value: |
        # Labs
        The [Labs stage](https://community.finos.org/docs/governance/lifecycle-stages/labs) is for projects in an experimental and exploratory phase.

  - type: dropdown
    id: entry_path
    attributes:
      label: Entry Path
      description: "Are you transitioning from Labs or contributing an existing advanced project?"
      options:
        - "Transitioning from FINOS Labs"
        - "Direct Entry (Advanced Contribution)"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "---"

  - type: markdown
    attributes:
      value: "## Labs Requirements"

  - type: checkboxes
    id: labs_requirements
    attributes: 
      label: Labs Compliance
      description: "Incubating projects must continue to meet all Labs-level standards."
      options:
        - label: "I confirm that the codebase meets [Labs Acceptance Requirements](https://community.finos.org/docs/governance/lifecycle-stages/labs/#labs-acceptance-requirements)"
          required: true
        - label: "I confirm that the codebase meets [Labs Ongoing Maintenance Requirements](https://community.finos.org/docs/governance/lifecycle-stages/labs/#labs-ongoing-maintenance-requirements)"
          required: true

  - type: markdown
    attributes:
      value: "---"

  - type: markdown
    attributes:
      value: "## Final Steps"

  - type: checkboxes
    id: badging_commitment
    attributes:
      label: Status Badging
      options:
        - label: "Project Team commits to adopt the [FINOS Labs badge](https://community.finos.org/docs/governance/lifecycle-stages/labs#badge) in the README.md once approved"
          required: true

  - type: markdown
    attributes:
      value: "---"

  - type: markdown
    attributes:
      value: "## Internal Operations (FINOS Staff Only)"

  - type: checkboxes
    id: internal_ops
    attributes:
      label: Operational Completion
      description: "This checkbox is for FINOS Staff use only."
      options:
        - label: "I confirm that all internal FINOS operational tasks related to this lifecycle transition have been completed."
    validations:
      required: false
