language: node_js
node_js:
  - '8'

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - website/node_modules
    - $HOME/.m2

before_install:
  - npm install -g ts-node
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc

script:
  # Build the website
  - cd website && yarn install && yarn run build && cd -

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN
    email: $GH_EMAIL
    name: $GH_NAME
    verbose: true
    keep-history: true
    local-dir: website/build/finos-pmcs
    target_branch: gh-pages
    on:
      branch: master
